# Run: cargo +nightly fmt
#
tab_spaces = 2
max_width = 85
single_line_if_else_max_width = 80
chain_width = 32
format_code_in_doc_comments = false
use_field_init_shorthand = true
#
wrap_comments = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_macro_matchers = true
condense_wildcard_suffixes = true
