[alias]
ta = ["test", "--all-features", "--workspace"]
open-doc = [
    "test",
    "--package",
    "testutils",
    "--test",
    "doc",
    "--all-features",
    "--",
    "build_and_open_rust_doc",
    "--exact",
    "--show-output",
    "--ignored",
]
